using ASI.Basecode.Data.Interfaces;
using ASI.Basecode.Data.Models;
using ASI.Basecode.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ASI.Basecode.Services.Services
{
    public class ExpenseService : IExpenseService
    {
        private readonly IExpenseRepository _expenseRepository;

        // Constructor
        public ExpenseService(IExpenseRepository expenseRepository)
        {
            this._expenseRepository = expenseRepository;
        }

        // Retrieves all expenses
        public List<Expense> GetExpenses()
        {
            var expenses = _expenseRepository.ViewExpenses().ToList(); // Convert IEnumerable to List
            return expenses;
        }

        // Adds a new expense
        public void AddExpense(Expense expense)
        {
            if (expense == null)
            {
                throw new ArgumentNullException(nameof(expense), "Expense cannot be null");
            }

            // Prepare a new expense object without setting ExpenseID (auto-generated by DB)
            var newExpense = new Expense
            {
                Title = expense.Title,
                Amount = expense.Amount,
                Date = expense.Date,
                CategoryID = expense.CategoryID,  // Assign the CategoryID foreign key here
                Description = expense.Description
            };

            _expenseRepository.AddExpense(newExpense);
        }

        // Updates an existing expense
        public void UpdateExpense(Expense expense)
        {
            if (expense == null)
            {
                throw new ArgumentNullException(nameof(expense), "Expense cannot be null");
            }

            _expenseRepository.UpdateExpense(expense);
        }

        // Deletes an expense
        public void DeleteExpense(Expense expense)
        {
            if (expense == null)
            {
                throw new ArgumentNullException(nameof(expense), "Expense cannot be null");
            }

            _expenseRepository.DeleteExpense(expense);
        }
    }
}